#page title
page_title                                : P24 Mobile SDK                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# P24 URL CONFIG
p24_docs_url                              : https://developers.przelewy24.pl/index.php?pl
p24_docs_title                            : Dokumentacja techniczna

p24_android_lib_url                       : https://github.com/przelewy24/p24-mobile-lib-android                                         
p24_flutter_lib_url                       : https://github.com/przelewy24/p24-mobile-lib-flutter                                          
p24_ios_lib_url                           : https://github.com/przelewy24/p24-mobile-lib-ios                                                            
p24_xamarin_lib_url                       : https://github.com/przelewy24/p24-mobile-lib-xamarin                                                            
p24_react_lib_url                         : https://github.com/przelewy24/p24-mobile-lib-react-native-example                                                            


#App config
app_icon                                  : assets/logo/favicon.ico                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_logo                                  : assets/logo/logo.png                     
app_name                                  : Biblioteki mobilne Przelewy24                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Zestaw bibliotek Przelewy24 przeznaczonych na najbardziej znane platformy mobilne
app_additional                            : Ponadto posiadamy biblioteki dla


enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Przelewy24                               
your_link                                 : https://przelewy24.pl                     


# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/background.jpeg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"


####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
